### ISSUE TITLE
Swift Project Integration Problem

### ISSUE THREAD

**Issue by hiroshi-shin** [hulop/HLPLocationManager#2]
I was trying to integrate the framework into both my swift and objc demo, and got the following results.

Device: Mac M1
Command: `carthage update --platform ios`

**1. objc**
`'HLPLocationManager.h' file not found`

**2. swift** (framework not added)
`No such module 'HLPLocationManager'`

**3. swift** (framework added, Do Not Embed)
`'/Path/To/Carthage/Build/iOS/HLPLocationManager.framework/HLPLocationManager' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Path/To/Carthage/Build/iOS/HLPLocationManager.framework/HLPLocationManager' for architecture arm64`

The error message for 2 was not appearing.

**Comment by daisukes** [comment]
Hi @hiroshi-shin 

I'm not sure exactly what you are trying to do, but I guess

> **1. objc**
> `'HLPLocationManager.h' file not found`

How about `#import "HLPLocationManager/HLPLocationManager.h"`?

> **2. swift** (framework not added)
> `No such module 'HLPLocationManager'`

You may need to add HLPLocationmanager as a framework.

> **3. swift** (framework added, Do Not Embed)
> `'/Path/To/Carthage/Build/iOS/HLPLocationManager.framework/HLPLocationManager' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Path/To/Carthage/Build/iOS/HLPLocationManager.framework/HLPLocationManager' for architecture arm64`

As the error shows, the HLPLocationManager does not have bitcode.
So you need to set `Enable Bitcode` in Build Settings to `NO`.

**Comment by hiroshi-shin** [comment]
@daisukes 
> As the error shows, the HLPLocationManager does not have bitcode.
> So you need to set Enable Bitcode in Build Settings to NO.

Thank you. That's exactly what I'm looking for.
